In [22]:
import os

In [23]:
import pandas as pd
df = pd.read_csv(r"C:\Users\naula\OneDrive\Desktop\Nasa Return 0\dataset\raw\raw_data.csv", comment="#", engine="python")
df.head()

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [24]:
drop_cols = [c for c in df.columns if "_err1" in c or "_err2" in c]
df = df.drop(columns=drop_cols, errors="ignore")

In [25]:
df.head()

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,93.59,35.8,1.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,9.11,25.8,2.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,39.30,76.3,1.0,q1_q17_dr25_tce,5853.0,4.544,0.868,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,891.96,505.6,1.0,q1_q17_dr25_tce,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,926.16,40.9,1.0,q1_q17_dr25_tce,6031.0,4.438,1.046,288.75488,48.226200,15.509

In [26]:
drop_id_cols = ["kepid", "kepoi_name", "kepler_name"]
df = df.drop(columns=[c for c in drop_id_cols if c in df.columns])

In [27]:
df.head()

,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_time0bk,koi_impact,...,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,CONFIRMED,CANDIDATE,1.000,0,0,0,0,9.488036,170.538750,0.146,...,93.59,35.8,1.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,CONFIRMED,CANDIDATE,0.969,0,0,0,0,54.418383,162.513840,0.586,...,9.11,25.8,2.0,q1_q17_dr25_tce,5455.0,4.467,0.927,291.93423,48.141651,15.347
2,CANDIDATE,CANDIDATE,0.000,0,0,0,0,19.899140,175.850252,0.969,...,39.30,76.3,1.0,q1_q17_dr25_tce,5853.0,4.544,0.868,297.00482,48.134129,15.436
3,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,1.736952,170.307565,1.276,...,891.96,505.6,1.0,q1_q17_dr25_tce,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,CONFIRMED,CANDIDATE,1.000,0,0,0,0,2.525592,171.595550,0.701,...,926.16,40.9,1.0,q1_q17_dr25_tce,6031.0,4.438,1.046,288.75488,48.226200,15.509

In [28]:
cat_cols = df.select_dtypes(include=["object"]).columns
for col in cat_cols:
    df[col] = df[col].astype("category").cat.codes

In [29]:
df.head()

,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_time0bk,koi_impact,...,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,1,0,1.000,0,0,0,0,9.488036,170.538750,0.146,...,93.59,35.8,1.0,2,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,1,0,0.969,0,0,0,0,54.418383,162.513840,0.586,...,9.11,25.8,2.0,2,5455.0,4.467,0.927,291.93423,48.141651,15.347
2,0,0,0.000,0,0,0,0,19.899140,175.850252,0.969,...,39.30,76.3,1.0,2,5853.0,4.544,0.868,297.00482,48.134129,15.436
3,2,1,0.000,0,1,0,0,1.736952,170.307565,1.276,...,891.96,505.6,1.0,2,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,1,0,1.000,0,0,0,0,2.525592,171.595550,0.701,...,926.16,40.9,1.0,2,6031.0,4.438,1.046,288.75488,48.226200,15.509

In [30]:
num_cols = df.select_dtypes(include=["float64", "int64"]).columns
df[num_cols] = df[num_cols].apply(lambda x: x.fillna(x.median()))

In [31]:
df.head()

,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_time0bk,koi_impact,...,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,1,0,1.000,0,0,0,0,9.488036,170.538750,0.146,...,93.59,35.8,1.0,2,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,1,0,0.969,0,0,0,0,54.418383,162.513840,0.586,...,9.11,25.8,2.0,2,5455.0,4.467,0.927,291.93423,48.141651,15.347
2,0,0,0.000,0,0,0,0,19.899140,175.850252,0.969,...,39.30,76.3,1.0,2,5853.0,4.544,0.868,297.00482,48.134129,15.436
3,2,1,0.000,0,1,0,0,1.736952,170.307565,1.276,...,891.96,505.6,1.0,2,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,1,0,1.000,0,0,0,0,2.525592,171.595550,0.701,...,926.16,40.9,1.0,2,6031.0,4.438,1.046,288.75488,48.226200,15.509

In [32]:
os.makedirs(os.path.dirname(r"C:\Users\naula\OneDrive\Desktop\Nasa Return 0\dataset\cleaned\cleaned_data.csv"), exist_ok=True)
df.to_csv(r"C:\Users\naula\OneDrive\Desktop\Nasa Return 0\dataset\cleaned\cleaned_data.csv", index=False)

In [33]:
df.columns

Index(['koi_disposition', 'koi_pdisposition', 'koi_score', 'koi_fpflag_nt',
       'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period',
       'koi_time0bk', 'koi_impact', 'koi_duration', 'koi_depth', 'koi_prad',
       'koi_teq', 'koi_insol', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_tce_delivname', 'koi_steff', 'koi_slogg', 'koi_srad', 'ra', 'dec',
       'koi_kepmag'],
      dtype='object')